### ISSUE TITLE
Adding Android Support

### ISSUE THREAD

**Issue by aantaya1** [mhshams/jnbis#26]
## The Issue:
The WSQ conversion does not work on Android since it uses the `java.awt.*` library which is not implemented in the Android SDK. As a result, you must use the `android.graphics.*` library. The only method that needed to be redone was the `BitmapHandler.convert()` method since it was the only one that used the awt library.

## The Solution:

**Note**: I changed the name of the `jnbis.Bitmap` class to be `MyImageBitmap` to avoid name space conflicts with `android.graphics.Bitmap`.

Here is my implementation of the `BitmapHandler.convert()` method:

```
/**
 * Converts the given <code>MyImageBitmap</code> to the specified image format and returns it as byte array.
 *
 * @param myImageBitmap the given bitmap, not null
 * @param format the given target image format, not null
 * @return the converted data in byte array format, not null
 */
private byte[] convert(MyImageBitmap myImageBitmap, String format) {
    int width = myImageBitmap.getWidth();
    int height = myImageBitmap.getHeight();

    byte[] imgRGB888 = myImageBitmap.getPixels();

    Bitmap bmp2 = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);

    int[] colors = new int[width * height];

    //We need to convert the image from a byte array to a
    // int color array so we can create the Android Bitmap
    int r,g,b;
    for (int ci = 0; ci < colors.length; ci++) {
        r = (int)(0x000000ff & imgRGB888[ci]);
        g = (int)(0x000000ff & imgRGB888[ci]);
        b = (int)(0x000000ff & imgRGB888[ci]);
        colors[ci] = Color.rgb(r, g, b);
    }

    bmp2.setPixels(colors, 0, width, 0, 0, width, height);

    Bitmap.CompressFormat compressFormat;

    if (format.equals("jpeg")){
        compressFormat = android.graphics.Bitmap.CompressFormat.JPEG;
    }else{//must be png
        compressFormat = android.graphics.Bitmap.CompressFormat.PNG;
    }

    try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()){
        bmp2.compress(compressFormat, 100, outputStream);
        return outputStream.toByteArray();
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

You will also need to remove the `java.awt.*` imports at the top of the class for this to compile.

This solution allowed me to convert WSQ images to JPEG byte arrays and display them in an `ImageView` no problem.

This is basically how I am using it:
```
byte[] wsqImageBytes = //get wsq image bytes from somewhere
byte[] convertedImageBytes = Jnbis.wsq().decode(wsqImageBytes).toJpg().asByteArray();
int len = convertedImageBytes.length;
Bitmap bmp = BitmapFactory.decodeByteArray(convertedImageBytes, 0, len, null);
imageView.setImageBitmap(bmp);
```

## Moving Forward:
- We might want to consider creating a fork of the project for Android.
- [Optional] The tests will need to be re-written to work in an Android environment.

## Extra Notes for Using This Library in Android:
- I cloned the repo and added it as a module in my Android project and made the changes in the module.
- I removed the tests since as they are written, they don't work in Android environment.

**Comment by mhshams** [comment]
hi @aantaya1 , thanks for this.  unfortunately i don't have time for this work. i would really appreciate it if you could make a PR for this.

**Comment by mhshams** [comment]
Closing this, since the proposed changes requires dependency to android platform.
